export const PageEnum = {
  Home: 'home',
  FrontendDevelopment: 'frontendDevelopment',
  Cms: 'cms',
  BackendDevelopment: 'backendDevelopment',
  UiUxDesign: 'uiUxDesign',
  Qa: 'qa',
  CustomService: 'customService',
  Web3: 'web3',
  OurWork: 'ourWork',
  AboutUs: 'aboutUs',
  ContactUs: 'contactUs',
  ForAgency: 'forAgency',
  ProjectDetail: 'projectDetail',
};
